### ISSUE TITLE
MithraGeneratorException with MithraEnumeration element

### ISSUE THREAD

**Issue by sett4** [goldmansachs/reladomo#105]
Hi.

I've got error MithraGeneratorException: unable to load template com.gs.fw.common.mithra.templates.enumeration.Main_jsp, make sure you have compiled the templates.

reladomo version 16.5.1.

TestEnum.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<MithraEnumeration
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="reladomoobject.xsd">
    <PackageName>sample.domain</PackageName>
    <ClassName>TestEnum</ClassName>
    <Member name="MEMBER1"/>
</MithraEnumeration>
```

ReladomoClassList.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Mithra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="reladomoobject.xsd"
        enableOffHeap="false">
    <MithraEnumerationResource name="TestEnum"/>
</Mithra>
```

Compile
```
$ mvn compile
.... snip ....
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (generateMithra) on project reladomo-sample-simple: An Ant BuildException has occured: com.gs.fw.common.mithra.generator.MithraGeneratorException: Failed to generate classes for TestEnum with nested exception com.gs.fw.common.mithra.generator.MithraGeneratorException: unable to load template com.gs.fw.common.mithra.templates.enumeration.Main_jsp, make sure you have compiled the templates -> [Help 1]
```

**Comment by gs-rezaem** [comment]
Sorry, Enumeration is a not a supported feature. It was half-implemented a long time ago and never completed. We'll have to remove it entirely to avoid this kind of confusion.

**Comment by sett4** [comment]
OK.
Is there any plans for enum support?

**Comment by gs-rezaem** [comment]
Any sort of wrapping can easily be done by putting methods in your concrete class that accept/return an enum. That allows a more flexible mapping (e.g. from an integer or two attributes, etc).
A long term goal is for us to have the ability to create "computed" attributes. Enums may be covered by that, although that hasn't been quite planned out yet.

**Comment by gs-rezaem** [comment]
Removed all this in 16.6.0
