### ISSUE TITLE
Mapping SqlServer nvarchar(..) fields to H2 test database

### ISSUE THREAD

**Issue by TMTHY** [goldmansachs/reladomo#108]
Hello
I work with SqlServer and I use **nvarchar** type for strings.  When I try to load my test data to **MithraTestResource** I have the problem with **maxLength** constraint - **nvarchar** is mapped to **varchar** in H2 test database, but length constraint stays the same. So, having some field declared as **nvarchar(100)**, in my test data file I can have value for that field with length, for example, 90. But when **MithraTestResource** tries to load that value to H2 database, it throws org.h2.jdbc.JdbcBatchUpdateException because values is too long for **varchar(100)** data type. And it is right - you need varchar(200) in H2 db to store nvarchar(100) values.

Is there any workaround for this?

**Comment by TMTHY** [comment]
The work around for this issue is to enforce single byte file encoding for test data files (for example, working with Cyrillic strings you can convert your file from UTF-8 to windows-1251 encoding). In most cases that can help

**Comment by gs-rezaem** [comment]
I'm glad you figured this out and shared the solution. It was new to me 😄 .
Out of curiosity, are you familiar with the DbExtractor util that comes with Reladomo? I would be curious to see what happens if you try using DbExtractor to extract Cyrillic characters from MsSQL.
