### ISSUE TITLE
Documentation for Source Connection Manager?

### ISSUE THREAD

**Issue by Zynde** [goldmansachs/reladomo#122]
Hi,

I was looking at the SourceAttribute to see how to make use of multiple databases. 

The documentation has this regarding the Source Connection Manager but I can'f find where the documentation is that details how to setup a Connection Manager class for multiple sources and sharding. Can you point me in the right direction?

> 3.1.2. Source Connection Manager
> In some cases, Reladomo objects come from multiple source databases. One common case where this can happen is if the database is sharded. In this case, the connection manager's job is to return a shard-specific database connection.
> 
> Sharding is discussed in more detail in other Reladomo documentation.

**Comment by gs-rezaem** [comment]
Look at the interface ```ObjectSourceConnectionManager```. A typical implementation is a map of source attribute value to ```XAConnectionManager```, but in your case (AWS Aurora), you might want to use a single ```XAConnectionManager``` and your connection manager implements both  ```ObjectSourceConnectionManager``` and ```ObjectSourceSchemaManager```. That depends on whether you like to have a single pool connecting to AWS or would prefer a different pool for each shard (e.g. for security reasons).
