### ISSUE TITLE
Make Reladomo build work with JDK 1.7+

### ISSUE THREAD

**Issue by itohiro73** [goldmansachs/reladomo#128]
Mac OS High Sierra cannot install JDK 1.6 any more and there is no way to build Reladomo in the OS unfortunately.

Is there any plans to make Reladomo build work with JDK 1.7+? If I can help in any ways I'm happy to contribute.

**Comment by gs-rezaem** [comment]
There is no plan to support jdk 1.7. We'll go to 1.8 sometime in the future. For now, you can use this [branch]( https://github.com/gs-rezaem/reladomo/tree/jdk18) to build with 1.8.
