### ISSUE TITLE
Add Eclipse Collections as a dependency.

### ISSUE THREAD

**Issue by itohiro73** [goldmansachs/reladomo#133]
(This is Hiroshi with my personal account)
 
Since my copyright situation got changed after I raised PR #30, I'm going to cancel #30 and submit a new PR with adding dco for EC dependency changes in reladomo.

I'm still in middle of making changes and I'd have design questions for the change, so would like to use this issue for discussion.

**Comment by itohiro73** [comment]
@gs-rezaem 

I find `Function` is passed in a method in `NumericAttribute` interface. I think there are couple of similar public method that takes GSC `Function`. How do you want to handle this kind of method that takes GSC `Function`?  

`NumericAttribute#getMappedAttributeWithCommonMapper(NumericAttribute calculatedAttribute, Mapper commonMapper, Mapper mapperRemainder, Function parentSelector)`

- Option1: Introduce a new `Function` interface (e.g. `ReladomoFunction` or any other good name?) that extends both GSC and EC Function, and replace the method signature with the new one
- Option2: Simply deprecate the current method, and add a new method that takes EC `Function`

How do you think, or any other options you like?

**Comment by gs-rezaem** [comment]
That method isn't very public (as in, I doubt any app code is calling it directly). That function, however, gets passed around and ends up where other Function objects are, some of which are code generated. So whatever choice we make here, will have a broader effect. I'll go with Option 1 (which will eventually have to implement java.util.Function probably via a default method).
Also, let's keep the discussion in the PR.
