### ISSUE TITLE
Getting exception when tried to join a table with equalsEdgePoint()

### ISSUE THREAD

**Issue by prdsharma** [goldmansachs/reladomo#150]
Getting below exception when tried to join table with equalsEdgePoint().

**Sample Reladomo Query:**
DocumentFinder.authors().processingDate().equalsEdgePoint()
.and(DocumentFinder.authors().processingDateTo().greaterThan(<anydate>))

**Exception :**
can't join with non-standard as-operation com.gs.fw.common.mithra.finder.asofop.AsOfEdgePointOperation processingDate

**Comment by prdsharma** [comment]
I need something like this.
`DocumentFinder.authors.processingDateTo().greaterThan(xDaysAgo)`

**Comment by mohrezaei** [comment]
Alternatively, try defining a new relationship to authors, where the relationship clause includes equalsEdgePoint. looks like this:
```xml
<Relationship name="itemsForAllTime" relatedObject="AuditedOrderItem"
 cardinality="one-to-many">
AuditedOrderItem.orderId = this.orderId and AuditedOrderItem.processingDate equalsEdgePoint
</Relationship>
```

**Comment by prdsharma** [comment]
As I need to use few complex queries and it seems very challenging in this way. Can you please let me know if there is any way to write object queries like HQL or native queries in reladomo.
