### ISSUE TITLE
Support for unicode encoded data files

### ISSUE THREAD

**Issue by kimptoc** [goldmansachs/reladomo#193]
Hi,

We have some data files that contain Unicode (non-ascii) characters that AbstractMithraDataFileParser is loading incorrectly on Linux - its using the default system charset/encoding - which is ASCII.  Works ok on Windows/windows-1252 :) 

One option is to set the default locale before starting Java, using 
  export LANG=en_US.UTF-8

Any plans to provide support to change the encoding within the parse method of the above FileParser, eg pass in a Charset that can be used with the InputStreamReader?

Cheers
Chris

**Comment by mohrezaei** [comment]
Supporting different charsets is a good idea. It's pretty straight forward. I'd suggest adding a method to the test resource to set the char encoding (instead of specifying it on each file). 

We'll happily accept a contribution, if you want to have a go at it.

**Comment by kimptoc** [comment]
Thanks - added to my backlog :(

**Comment by mohrezaei** [comment]
This is implemented in #197. Will be released next week in 17.1.0

**Comment by kimptoc** [comment]
Awesome!  Many thanks @mohrezaei
