### ISSUE TITLE
Using reladomo to connect to Oracle database

### ISSUE THREAD

**Issue by sameerswami85** [goldmansachs/reladomo#199]
Trying to create connection to an Oracle d/b using reladomo 17.1.0. Below is the snippet for OracleConnectionManager.java
XAConnectionManager xaConnectionManager = new XAConnectionManager();
xaConnectionManager.setDriverClassName("oracle.jdbc.driver.OracleDriver");
xaConnectionManager.setHostName(host);
xaConnectionManager.setPort(port);
xaConnectionManager.setJdbcUser(username);
xaConnectionManager.setJdbcPassword(password);
xaConnectionManager.setMaxWait(500);
xaConnectionManager.setPoolSize(10);
xaConnectionManager.setInitialSize(1);
xaConnectionManager.initialisePool();

While trying to create the connection, following error is thrown
java.lang.ClassNotFoundException: com.gs.fw.common.mithra.connectionmanager.JndiJdbcLdapDataSourceProvider

JndiJdbcLdapDataSourceProvider was not part of reladomo:17.1.0 jar downloaded. 
Looked through the source and noticed reference to com.gs.fw.aig.jdbc.JdbcInitialDirContext; which was also not part of the jar. https://github.com/goldmansachs/reladomo/blob/17.1.0/reladomogs/src/main/java/com/gs/fw/common/mithra/connectionmanager/JndiJdbcLdapDataSourceProvider.java

Please let us know if there is an alternate way we we can take to connect to Oracle.

**Comment by mohrezaei** [comment]
You have to set the JdbcConnectionString. Something like:
```java
xaConnectionManager.setJdbcConnectionString("jdbc:oracle:thin:@"+hostname+":"+port+":"+ssid);
```

**Comment by sameerswami85** [comment]
Thank you, that worked.
