### ISSUE TITLE
Strings should be quoted in the toString() representation of in-clause operations.

### ISSUE THREAD

**Issue by motlin** [goldmansachs/reladomo#224]
```java
Operation operation1 = MyTypeFinder.myProperty().eq("myString 1");
Operation operation2 = MyTypeFinder.myProperty().in(new LinkedHashSet<>(Arrays.asList("myString 1", "myString 2")));
System.out.println(operation1);
System.out.println(operation2);
```

prints:
```
MyType.myProperty = "myString 1"
MyType.myProperty in [myString 1, myString 2]
```

Strings are quoted in NonPrimitiveEqOperation but not in NonPrimitiveInOperation. I think this may just require an override to NonPrimitiveInOperation#appendSetToString and NonPrimitiveNotInOperation#appendSetToString, but I wanted to check here before submitting a PR.

**Comment by mohrezaei** [comment]
A PR would be appreciated.
