### ISSUE TITLE
ObjectSequenceAbstract.java not found

### ISSUE THREAD

**Issue by greensuse** [goldmansachs/reladomo#245]
in the reladomo-sample-simple project, there is code like below

public class ObjectSequence extends ObjectSequenceAbstract implements MithraSequence
{

where is the java class ObjectSequenceAbstract  come from?
I do not see it in master branch?

**Comment by mohrezaei** [comment]
The abstract classes are code generated during the build.

**Comment by marcos96tavares** [comment]
ObjectSequenceAbstract is a custom class that is built during the project development process. It serves as an abstract class, providing a blueprint or set of rules that other classes can follow when extending it. In the case of ObjectSequence, it extends ObjectSequenceAbstract, indicating that ObjectSequence is a subclass that inherits and extends the functionality and structure defined in ObjectSequenceAbstract.

In Java, an abstract class serves as a partial implementation, allowing common functionality to be shared among its subclasses while enforcing certain rules and guidelines for their construction. By extending the abstract class, ObjectSequence adheres to these rules and inherits any shared behavior or characteristics defined in ObjectSequenceAbstract. This promotes code reusability and helps maintain consistency across different classes that utilize the abstract class as their base.
