### ISSUE TITLE
H2 Database 2.1.210 to Mithra integration failing for InMemory database

### ISSUE THREAD

**Issue by vaidyapawan** [goldmansachs/reladomo#252]
After updating the version for H2Database to 2.1.210, test cases which include any Mithra method reference starts failing. It shows as "IS_DEFAULT" column is missing. We don't have any such column in any of our table (So that cancels the case-sensitivity issue). When ran with debug mode, it shows that the error is coming from ResultSet class. Anyone faced similar issue? Do we have any timeline on fixing this new H2 database version synch issue with reladomo/Mithra?

**Comment by vaidyapawan** [comment]
It gets stuck while verifying the InMemoryDatabase, saying "IS_DEFAULT" column is missing.

**Comment by mohrezaei** [comment]
Version 18.1.0 was released last month with H2 2.x support.
