### ISSUE TITLE
DB Support for Snowflake / Redshift 

### ISSUE THREAD

**Issue by SUNDSU** [goldmansachs/reladomo#253]
We are migrating our data from Sybase IQ to Cloud DB ( snowflake or Redshift ) and looking for Reladomo support for cloud DB's .

**Comment by mohrezaei** [comment]
Supporting a new DB is relatively straight forward.

Redshift is mostly Postgres compatible, so you can just try it with `PostgresDatabaseType`.

Snowflake will likely require some development. A good starting point is probably something reasonably standard like Postgres.

Whoever is doing the implementation will need a test instance and can copy the existing DB specific tests as a starting point.

**Comment by SUNDSU** [comment]
sure @mohrezaei ..let me look in to Postgress ( Redshift ) option as a first step to evaluate our cloud migration strategy.
