### ISSUE TITLE
Upgrade H2 version 2.1.210 from 1.4.200

### ISSUE THREAD

**Issue by mavericksgeek** [goldmansachs/reladomo#257]
Hello, 
We are trying to upgrade 2.1.210 from 1.4.200 due to vulnerability. We are using the latest reladomo version 18.1.0, but we are facing this error of JdbcSQLNonTransientConnectionException with unknown legacy mode, while creating a connection to a pooled resource in tests. This works completely well in the first module of our project but errors out in our JDBC connection string to create a connection. The following exception is thrown : 

`org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unknown mode "LEGACY" [90088-200]`

Could you suggest a fix for this?

**Comment by mohrezaei** [comment]
What version of Reladomo are you using? 18.1.0 was released a year ago with support for H2 2.x

**Comment by mavericksgeek** [comment]
We are using Reladomo 18.1.0, that has h2 version of 2.1.210. So, the initial test cases were written using Reladomo 17.0.2 where we used the h2 version of 1.4.2

**Comment by mohrezaei** [comment]
Check your classpath. You probably have some old jars in there. If not, please provide a reproducible test case.

**Comment by mavericksgeek** [comment]
I have removed any previous folder from my Gradle build having h2 1.4.2, but when try building it shows fails. When I ran the dependencies command of Gradle it shows the following : 
```
|    |    +--- com.goldmansachs.reladomo:reladomo-test-util:18.1.0
|    |    |    +--- com.goldmansachs.reladomo:reladomo:18.1.0 (*)
|    |    |    \--- com.h2database:h2:2.1.210 -> 1.4.200
```
Only when we exclusively provide dependency for h2:2.1.210 as below  and exclude it from Reladomo, it is successful. `testImplementation ("com.h2database:h2:${versions.h2}")`

**Comment by mohrezaei** [comment]
If I understand this correctly, this is an issue with your build script, as there is no reference to the older H2 versions in the Reladomo pom files.
From the dependency output above, it's clear that Gradle is downgrading H2, so you'll have to figure that out.

Closing as not a Reladomo issue.

**Comment by mavericksgeek** [comment]
Great! Just figured out when you mentioned , issue Gradle build scrip and after looking through some docs on SpringBoot. So, we are using SpringBoot 2.5.12, the POM of which in Gradle folders mentions the h2 version to 1.4.2, which is reason for downgrading it to 1.4.2
