### ISSUE TITLE
How To Question: Many-to-many example

### ISSUE THREAD

**Issue by mbarzim** [goldmansachs/reladomo#267]
Is anyone aware of an example of many-to-many relationship insertion? Given a relationship definition [similar to this](https://github.com/goldmansachs/reladomo/blob/master/reladomo/src/doc/docbook/mithrafaq/ReladomoFaq.xml#L75) or as defined in [AuditedUser.xml](https://github.com/goldmansachs/reladomo/blob/master/reladomo/src/test/reladomo-xml/AuditedUser.xml#L36) and joined through junction table [AuditedUserGroup.xml](https://github.com/goldmansachs/reladomo/blob/master/reladomo/src/test/reladomo-xml/AuditedUserGroup.xml#L30), I would expect something like this to work: 
```java

//Create a new user who is a member of pre-existing groups
AuditedGroupList groups = ;//A list of AuditedGroups
AuditedUser user = ; // A single user

// ...user instantiation and property setting...
user.setGroups(groups);
user.cascadeInsert();

```

The result I would expect here is one inserted row in the AuditedUserGroup table, per group.

When I'm doing something similar however, the `cascadeInsert` doesn't seem to create the desired entries. 

Can someone point me in the right direction here? Happy to submit a PR to update documentation once we clarify.

**Comment by mohrezaei** [comment]
You don't have to wire the object graph together to get relationships to work in Reladomo. 
The simplest approach is just to insert whatever you want -- relationships will just work. 

In case of many-to-many, you can insert the entries into the middle table.

If you want to do cascadeInsert, you have to mark the **middle table** as a dependent, set those and then cascade insert.

**Comment by mbarzim** [comment]
Excellent that's very helpful - many thanks
