### ISSUE TITLE
Reladomo Object XML Generator -> Postgresql support

### ISSUE THREAD

**Issue by ramtej** [goldmansachs/reladomo#85]
Hi, 

[https://goldmansachs.github.io/reladomo/objectxmlgenerator/Generator.html](url) describes that the Reladomo Mithra XML generator (reverse generation from an existing database) is capable to connect "sybase" and "udb82" databases. Any "hard" reasons why this is the case ? Or asked differently - what is required to be able to connect e.g. postgresql ?

Thank you. 
Best Regards, 
jj

**Comment by gs-rezaem** [comment]
Historically, we haven't had existing schemas in postgresql, so we haven't gotten around to building that yet. Said differently, we were waiting for someone to need it before implementing :smile: and we'd love a contribution.
See the class MithraObjectXmlGenerator and look at how DB_NAME_SYBASE is used, then add enough code for postgresql to wire it in. From there, it's just a matter of testing and making sure we handle the meta data coming back from the database correctly (via the PostgresDatabaseType class).

**Comment by ramtej** [comment]
Ok, see the point ! :-) I already take a look on MithraObjectXmlGenerator, TableInfo .. and from a quick & naive view, there should not be a show stopper. Ok, will give it a try.

**Comment by ramtej** [comment]
Question - is ther easy/preferred way how to import the project in an IDE, e.g. Intellij ? Of course, I can download the (transitive) dependencies using the ant build.xml script and then manually create the project. Is that the preferred way, or is there any xyz.sh script that is creating the corresponding IDE project files ? Otherwise, what about to use e.g. Gradle ?

**Comment by gs-rezaem** [comment]
I have project files here: https://github.com/gs-rezaem/cfgsync/tree/master/idea/reladomo
We're not likely to entertain changing the build system because of IDE project files.

**Comment by gs-rezaem** [comment]
Postgres xml generation code is committed. It'll be released in 16.5.0 soon.

**Comment by ramtej** [comment]
Thank you - will take a look on it!

**Comment by ramtej** [comment]
Hi, 
the reversal generation from an existing postgresql schema works for me. Thank you. I had some issues and have some proposals : 

1) Error ...../reladomo/lib/drivers does not exist.
It seems that is is required to manually create the $RELADOMO_HOME/lib/drivers directory 
before the <reladomo-gen-xml/> ant tasks can be executed

2) Java 6 JDBC Driver required
In case of Postgresql this is the PostgreSQL JDBC 4.0 Driver, 42.1.3.jre6
(https://jdbc.postgresql.org/download/postgresql-42.1.3.jre6.jar)

In general, I would like to see those low level things automated. 

3) The generated <MithraObject/> does not contain the package name: 
`    <PackageName>INSERT PACKAGE HERE</PackageName>
`
This is clearly just a little detail, but I used a postgresql schema with 50+ Entities for testing and it is pretty time consuming to add the package name. Evtl. the <reladomo-gen-xml/> ant tasks can contain the package name and add it to the generated files ? 

Will keep you posted with my progress on the postgresql topic. 

Thank you. 

Best Regards, 
jj

**Comment by gs-rezaem** [comment]
1. The postgres drivers: I'll move the driver from the private repo download to maven central download, as it's open source (unlike most of the other dbs we support). 
2. The driver we test with is this: org.postgresql,postgresql,9.3-1101-jdbc4.  See reladomogs.spec
3. The package is already a parameter to the task: generatedPackageName="com.whatever.you.like"
