### ISSUE TITLE
reladomo.iml in .gitignore

### ISSUE THREAD

**Issue by henohenotsuyoshi** [goldmansachs/reladomo#91]
Hi all,why is reladomo.iml in ignored files ?
I believe it will help us to set up dev environment swiftly in intellij.

**Comment by ramtej** [comment]
The reasons (I guess) is because the reladomo.iml is in another repository : 

https://github.com/gs-rezaem/cfgsync/tree/master/idea/reladomo

This is due to the fact, that reladomo uses an ant based build system, that is not directly supported by modern IDEs, such as intellij. 

Best Regards, 
jj

**Comment by gs-rezaem** [comment]
We don't support any particular IDE. Having that entry in the .gitignore file prevents accidental check-ins.
