### ISSUE TITLE
Reladomo Object XML Generator / Postgresql UUID Type

### ISSUE THREAD

**Issue by ramtej** [goldmansachs/reladomo#92]
Hi, 
I have a postgresql schema with a table defined as : 

`CREATE TABLE public.sampler_color
(
  id uuid NOT NULL,
  version integer NOT NULL,
`

The attribute id has a type  'uuid'

The Mithra XML Generator generates for this postgresql schema the following definition : 

 `    <Attribute name="id" javaType="uuid" primaryKey="true" columnName="id" />
`

which is not valid, as "uuid" is not a type. 

EclipseLink uses for example "java.util.UUID" for the postgresl uuid type. 

I tried to add

`        sqlToJavaTypes.put("uuid", "java.util.UUID");
`
to PostgresDatabaseType.java but then the Type has to be know also by MithraObjectTypeWrapper.java

`    private static Set<String> primitiveTypes = new HashSet<String>(Arrays.asList("boolean", "int", "long", "float", "double", "short", "byte", "char"));
    private static Set<String> javaTypes = new HashSet<String>(Arrays.asList("String", "Timestamp", "Date", "byte[]", "BigDecimal", "Time"));
`

.. not sure what the impact will be, how the mapping sql/java is done, etc. 

As a workaround the postgresql uuid can be intepreted evtl. as Java String ?

Best Regard, 
jj

**Comment by gs-rezaem** [comment]
We don't support a UUID java type or any other DB specific type that is has no JDBC equivalent (see java.sql.Types). 

If the postgres driver properly handles get/setString for such a column, then you can use javaType="String" in the xml.
You can add methods to your concrete class that represent this value as a custom type. For example, you can name the persistent attribute "idAsString" and add methods to get/setId as java.util.UUID by calling get/setIdAsString.
