### ISSUE TITLE
Connection Manager for NoSQL Databases

### ISSUE THREAD

**Issue by gcherian** [goldmansachs/reladomo#94]
Is it possible/feasible to create a Mithra Connection Manager for NoSQL Databases:

1. Hbase - say using Phoenix JDBC Driver: 
https://github.com/apache/phoenix/blob/master/phoenix-core/src/main/java/org/apache/phoenix/jdbc/PhoenixDriver.java
2. Spark - say using Databricks JDBC Driver https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/rdd/JdbcRDD.scala

Thanks,
George

**Comment by gs-rezaem** [comment]
That's not likely to be useful. The database has to be able to support SQL. That means everything, for example, joins.

**Comment by motlin** [comment]
What about BigQuery? They have [JDBC drivers](https://cloud.google.com/bigquery/partners/simba-drivers/) that support [a read-only subset of standard sql](https://cloud.google.com/bigquery/docs/reference/standard-sql/). What do you think? One potential obstacle is that they [do not support CREATE TABLE](https://cloud.google.com/bigquery/partners/simba-drivers/#do_the_drivers_provide_the_ability_to_manage_tables_eg_create_table) statements.

**Comment by gs-rezaem** [comment]
Create table is pretty important, so is writability with ACID. Phoenix seems to support both (even though there is no concept of temp tables). 
An important part of the Reladomo's philosophy is to use the storage as private storage. Clearly, with a read-only view that's not achievable.
It would be interesting to compare Amazon Aurora & Phoenix and possibly support them if they provide advantages over existing solutions.
