### ISSUE TITLE
MithraObjectXmlGenerator on MsSql - provide schema name parameter or ignore system schemas

### ISSUE THREAD

**Issue by TMTHY** [goldmansachs/reladomo#98]
There is no way to provide sql schema name for MithraObjectXmlGenerator (because of initializeSchemaOrCatalog method logic, "schemaName" variable is always null for SqlServer). 

SQL server database always contains system views and tables, so running MithraObjectXmlGenerator  leads to processing all those system views and tables. In my sample DB there are 400 system views (INFORMATION_SCHEMA.* and sys.*) for 20 user tables, so the output of generator is nearly unusable
(and on SqlServer 2012 generator actually throws exception trying to process sys.trace_xe_action_map table)

The work around is to provide "includeTables" parameter, but for real db that list would be very long.

**Comment by gs-rezaem** [comment]
There is a schema name parameter: ```schema = "someSchema"```. I just tested it and the output does not include any system tables when set to a proper schema.

**Comment by TMTHY** [comment]
using 16.5.1:
setup:
ant.mithraGenXml(userName: "sa",
            password: "xxxx",
            schema: "dbo",
            databaseType: "mssql",
            driver: "net.sourceforge.jtds.jdbc.Driver",
            url: "jdbc:jtds:sqlserver://127.0.0.1:1433/DBNAME",
output:
java.sql.SQLException: Database 'dbo' does not exist. Make sure that the name is entered correctly

setup:
ant.mithraGenXml(userName: "sa",
            password: "xxxx",
            schema: "DBNAME",
            databaseType: "mssql",
            driver: "net.sourceforge.jtds.jdbc.Driver",
            url: "jdbc:jtds:sqlserver://127.0.0.1:1433/DBNAME",

OK, but system tables included.

The code in MithraObjectXmlGenerator.initializeSchemaOrCatalog shows that "schema"  is applied as database name, and schemaName parameter is always null for SqlServer:
if ( ... databaseType.equalsIgnoreCase(DB_NAME_MSSQL))  {
   this.schemaName = null;
   this.catalog = schema;
 }

**Comment by gs-rezaem** [comment]
You're using the wrong drivers. Please use the ones from Microsoft. Specifically:
```
<dependency>
	<groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
	<version>6.2.1.jre8</version>
</dependency>
```

**Comment by TMTHY** [comment]
Using Micrisoft driver doesn't change anything:

setup:
ant.mithraGenXml(userName: "sa",
            password: "xxx",
            schema: "dbo",
            databaseType: "mssql",
            driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver",
            url: "jdbc:sqlserver://127.0.0.1:1433; databaseName=DBNAME"

result:
com.microsoft.sqlserver.jdbc.SQLServerException: Database 'dbo' does not exist. Make sure that the name is entered correctly.

May be we are using different reladomo versions?

**Comment by gs-rezaem** [comment]
Sorry, the word "schema" is highly overloaded. Try this: remove "databaseNAme=DBNAME" from the url, and set the ```schema:"DBNAME"```

**Comment by TMTHY** [comment]
It works both ways. I can provide url to sql server, and dbname in "schema" parameter, it's all ok, but I have no place to provide database schema name (dbo, for example). So, to process only "dbo" schema in my database, I have to use includeTables parameter. That is not a show stopper, that list can be created using a simple query, but it is greatly decreases usability of the xml generator. 

The "schema" parameter of MithraObjectXmlGenerator is overloaded in the wrong way. It is used to specify either database name (catalog variable) or database schema name (schemaName variable). But for SqlServer you need both - database name and database schema name.  

So, in method MithraObjectXmlGenerator .getTableNameListByTypes, while calling 
rs = metaData.getTables(catalog, schemaName, "%", types); (624) you need both catalog and schema name not to be null. But that is impossible.
