### ISSUE TITLE
MithraObjectXmlGenerator  / MsSql nvarchar type 

### ISSUE THREAD

**Issue by TMTHY** [goldmansachs/reladomo#99]
Having table defined as follows:

create table dbo.Citizen(Id int not null, Address nvarchar(500) null...)

MithraObjectXmlGenerator generates the following definition:

<Attribute name="address" javaType="nvarchar" columnName="Address" />

"nvarchar" is not valid type - it should be String

**Comment by gs-rezaem** [comment]
Thanks for the report. Incidentally, be careful with MsSQL drivers. The newer ones have a bug. The version certified with Reladomo is sqljdbc4-2.0.
